"""create worker_payments and additional_work

Revision ID: 4006c8a8d5ee
Revises: 7a1c9e4f2b3d
Create Date: 2026-09-14 17:01:24.696127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4006c8a8d5ee'
down_revision: Union[str, None] = '7a1c9e4f2b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_work',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_additional_work_amount_positive'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_additional_work_business_id'), 'additional_work', ['business_id'], unique=False)
    op.create_index(op.f('ix_additional_work_date'), 'additional_work', ['date'], unique=False)
    op.create_index(op.f('ix_additional_work_worker_id'), 'additional_work', ['worker_id'], unique=False)
    op.create_table('worker_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_type', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('payment_details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("payment_method IN ('cash', 'bank')", name='ck_worker_payment_method_enum'),
    sa.CheckConstraint("payment_type IN ('advance', 'salary', 'extra_work')", name='ck_worker_payment_type_enum'),
    sa.CheckConstraint('amount > 0', name='ck_worker_payment_amount_positive'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_payments_business_id'), 'worker_payments', ['business_id'], unique=False)
    op.create_index(op.f('ix_worker_payments_date'), 'worker_payments', ['date'], unique=False)
    op.create_index(op.f('ix_worker_payments_worker_id'), 'worker_payments', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_payments_worker_id'), table_name='worker_payments')
    op.drop_index(op.f('ix_worker_payments_date'), table_name='worker_payments')
    op.drop_index(op.f('ix_worker_payments_business_id'), table_name='worker_payments')
    op.drop_table('worker_payments')
    op.drop_index(op.f('ix_additional_work_worker_id'), table_name='additional_work')
    op.drop_index(op.f('ix_additional_work_date'), table_name='additional_work')
    op.drop_index(op.f('ix_additional_work_business_id'), table_name='additional_work')
    op.drop_table('additional_work')
    # ### end Alembic commands ###
