"""create attendance_entries

Revision ID: 43f7d5024612
Revises: d3588e207d21
Create Date: 2026-09-13 18:08:00.712978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f7d5024612'
down_revision: Union[str, None] = 'd3588e207d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('wage_at_entry', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('value IN (0, 0.5, 1.0, 1.25, 1.5)', name='ck_attendance_value_enum'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'site_id', 'date', name='uq_attendance_worker_site_date')
    )
    op.create_index(op.f('ix_attendance_entries_business_id'), 'attendance_entries', ['business_id'], unique=False)
    op.create_index(op.f('ix_attendance_entries_date'), 'attendance_entries', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_entries_worker_id'), 'attendance_entries', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_entries_worker_id'), table_name='attendance_entries')
    op.drop_index(op.f('ix_attendance_entries_date'), table_name='attendance_entries')
    op.drop_index(op.f('ix_attendance_entries_business_id'), table_name='attendance_entries')
    op.drop_table('attendance_entries')
    # ### end Alembic commands ###
