"""add start_date to sites

Revision ID: 602fe0ecd5a7
Revises: 43f7d5024612
Create Date: 2026-09-13 19:02:27.119155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602fe0ecd5a7'
down_revision: Union[str, None] = '43f7d5024612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'start_date')
    # ### end Alembic commands ###
