"""create site_expenses

Revision ID: 607f96c177fa
Revises: 4006c8a8d5ee
Create Date: 2026-09-14 19:39:14.250323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607f96c177fa'
down_revision: Union[str, None] = '4006c8a8d5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('paid_by', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("paid_by IN ('contractor', 'supervisor')", name='ck_site_expense_paid_by_enum'),
    sa.CheckConstraint("payment_method IN ('cash', 'bank')", name='ck_site_expense_payment_method_enum'),
    sa.CheckConstraint('amount > 0', name='ck_site_expense_amount_positive'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_expenses_business_id'), 'site_expenses', ['business_id'], unique=False)
    op.create_index(op.f('ix_site_expenses_date'), 'site_expenses', ['date'], unique=False)
    op.create_index(op.f('ix_site_expenses_site_id'), 'site_expenses', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_expenses_site_id'), table_name='site_expenses')
    op.drop_index(op.f('ix_site_expenses_date'), table_name='site_expenses')
    op.drop_index(op.f('ix_site_expenses_business_id'), table_name='site_expenses')
    op.drop_table('site_expenses')
    # ### end Alembic commands ###
