"""create client_bills and bill_receipts

Revision ID: d3f706f2ffac
Revises: 607f96c177fa
Create Date: 2026-09-14 19:56:13.381049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f706f2ffac'
down_revision: Union[str, None] = '607f96c177fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('bill_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('bill_amount > 0', name='ck_client_bill_amount_positive'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_bills_bill_date'), 'client_bills', ['bill_date'], unique=False)
    op.create_index(op.f('ix_client_bills_business_id'), 'client_bills', ['business_id'], unique=False)
    op.create_index(op.f('ix_client_bills_site_id'), 'client_bills', ['site_id'], unique=False)
    op.create_table('bill_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('amount_received', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("payment_method IN ('cash', 'bank')", name='ck_bill_receipt_payment_method_enum'),
    sa.CheckConstraint('amount_received > 0', name='ck_bill_receipt_amount_positive'),
    sa.ForeignKeyConstraint(['bill_id'], ['client_bills.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_receipts_bill_id'), 'bill_receipts', ['bill_id'], unique=False)
    op.create_index(op.f('ix_bill_receipts_business_id'), 'bill_receipts', ['business_id'], unique=False)
    op.create_index(op.f('ix_bill_receipts_date_received'), 'bill_receipts', ['date_received'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_receipts_date_received'), table_name='bill_receipts')
    op.drop_index(op.f('ix_bill_receipts_business_id'), table_name='bill_receipts')
    op.drop_index(op.f('ix_bill_receipts_bill_id'), table_name='bill_receipts')
    op.drop_table('bill_receipts')
    op.drop_index(op.f('ix_client_bills_site_id'), table_name='client_bills')
    op.drop_index(op.f('ix_client_bills_business_id'), table_name='client_bills')
    op.drop_index(op.f('ix_client_bills_bill_date'), table_name='client_bills')
    op.drop_table('client_bills')
    # ### end Alembic commands ###
